### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by zgiles** [rafipass/lsf-stats#2]
Hello,

What is the license for this code?
I'm interested in releasing a version of lsf.py from the lsf_bindings folder, but heavily rewrote it.
Your license looks very similar to MIT, but doesn't say that it is. 

Is it OK that I put my modified version under MIT and mention it is based on your's?

-Zach

**Comment by Mondale-tw** [comment]
I am fine with that. Let's wait for Rafi's reply. If you have a better version of lsf.py, we would consider pull your codes back here and some of our private repositories too.

-Mondale

**Comment by rafipass** [comment]
MIT is fine yeah.

**Comment by zgiles** [comment]
sweet. thanks guys. I'll post a link to what I put so you can see it too.

Mondale, not sure if it would be enough to copy back, but you're welcome to, or perhaps we could abstract it more and make something higher level we can both include.. but that's what the LSF api is for.. so.. idk

**Comment by zgiles** [comment]
For reference: https://github.com/zgiles/lsf-graphs
